repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-added-large-files
        args: [ '--maxkb=1024' ]
      - id: mixed-line-ending
        args: ["--fix", "lf"]


  - repo: local
    hooks:
      - id: go-fmt
        name: go format
        language: system
        entry: gofmt
        types:
          - go
        args: ["-l", "-w"]

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-build
      - id: go-mod-tidy
  - repo: local
    hooks:
      - id: go-test
        name: go test
        language: system
        entry: go
        args: ["test", "./..."]
        pass_filenames: false
        always_run: true
