apiVersion: v1
kind: Service
metadata:
  name: {{ .serviceName }}
  namespace: {{ .namespace }}
spec:
  type: {{ .serviceType }}
  {{- if .selector }}
  selector:
    {{- .selector | toYaml | nindent 4 -}}
  {{- else }}
  selector:
    app: {{ .serviceName }}
  {{- end }}
  ports:
    - protocol: TCP
      port: {{ default .targetPort .port  }}
      targetPort: {{ default .targetPort .port }}
      {{- if and (or ( eq .serviceType "NodePort" ) ( eq .serviceType "LoadBalancer") ) .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
