on:
  pull_request:
    branches:
      - main
  push:

jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'
      - name: Run tests
        run: go test -v ./cmd/yutc
